[package]
name = "ghostblade"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
rand = "0.9"

[lib]
name = "ghostblade"
path = "src/lib.rs"

[[bin]]
name = "ghostblade"
path = "src/main.rs"